### ISSUE TITLE
Repo status

### ISSUE THREAD

**Issue by ajsb85** [stephendpmurphy/serial-monitor#1]
Hi, @stephendpmurphy 

Can I help you building this app?

BTW, you should add the WIP status badge.

https://www.repostatus.org/

**Comment by stephendpmurphy** [comment]
Absolutely. Any help is welcome! I'll get the badge added, as well as begin filling out the README with project info, and first time installation instructions as I had a couple issues with getting the "serial-port" package to work well with Electron out of the box.
